# Generated by Django 5.2.4 on 2025-07-22 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrainageZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('elevation', models.FloatField()),
                ('drainage_capacity', models.FloatField()),
                ('geojson', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloodRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drainage.drainagezone')),
            ],
        ),
        migrations.CreateModel(
            name='RainfallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('rainfall_mm', models.FloatField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drainage.drainagezone')),
            ],
        ),
    ]
